# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: publish parquet file

on:
  push:
    tags:        
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  RawDataDirectory: ${{ github.workspace}}/raw
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dump-parquet:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file-name:
          - FY2021_Q1
          - FY2021_Q2
          - FY2021_Q3
          - FY2021_Q4
          - FY2022_Q1
          - FY2022_Q2
          - FY2022_Q3
          - FY2022_Q4
          - FY2023_Q1
          - FY2023_Q2
          - FY2023_Q3
          - FY2023_Q4
    steps:
      - uses: actions/checkout@v3
      - name: Setup python sqlite-utils
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: |
          import pandas
          df = pandas.read_excel('https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/LCA_Disclosure_Data_${{ matrix.file-name }}.xlsx', 
            nrows= 99, 
            converters={
              'VISA_CLASS':str,
              'SOC_CODE':str,
              'SOC_TITLE':str,
              'EMPLOYER_NAME':str,
              'EMPLOYER_CITY':str,
              'EMPLOYER_STATE':str,
              'EMPLOYER_POSTAL_CODE':str,
              'WORKSITE_CITY':str,
              'WORKSITE_STATE':str,
              'WORKSITE_POSTAL_CODE':str,
              'JOB_TITLE':str,
              'CASE_STATUS':str,
              'EMPLOYER_ADDRESS1': str,
              'EMPLOYER_ADDRESS2': str
            })
          df = df.loc[:, ['CASE_NUMBER', 'CASE_STATUS', 'RECEIVED_DATE', 'DECISION_DATE', 'ORIGINAL_CERT_DATE', 
                    'VISA_CLASS', 'JOB_TITLE', 'SOC_CODE', 'SOC_TITLE', 'FULL_TIME_POSITION', 
                    'BEGIN_DATE', 'END_DATE', 'TOTAL_WORKER_POSITIONS', 'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 
                    'CHANGE_PREVIOUS_EMPLOYMENT', 'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION', 
                    'EMPLOYER_NAME', 'EMPLOYER_ADDRESS1', 'EMPLOYER_ADDRESS2', 'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
                    'WORKSITE_CITY', 'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE',
                    'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY']]
          df.to_parquet('${{ matrix.file-name }}.parquet')
        shell: python
          
      - name: Upload artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file-name }}
          if-no-files-found: error
          path: ${{ github.workspace}}/*.parquet
          retention-days: 1
  deploy-to-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: dump-parquet
    if: success()
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Download artifacts 🔧
        uses: actions/download-artifact@v3
        with:
          path: parquet_dumps
      - name: Create build directory
        run: |
          mkdir -p build/data
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: |
          from pathlib import Path
          import pandas as pd

          data_dir = Path('parquet_dumps')
          full_df = pd.concat(
              pd.read_parquet(parquet_file)
              for parquet_file in data_dir.rglob('*.parquet')
          )
          full_df.to_parquet('build/data/db.parquet')
        shell: python
        
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build # The folder the action should deploy.
      #     clean: true # Automatically remove deleted files from the deploy branch
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/data/db.parquet
